templates = ['Someone mentioned the {word}.',
             'The post was about the {word}.',
             'Everyone was talking about the {word}.',
             'They were all interested in the {word}.',
             'People know about the {word}.']

gerneral_caption_like_templates = ['{article} {word}',
                          'There is {article} {word}']

per_category_templates = {'food': ['There is {article} {word} on a table in a restaurant.',
                                   '{article} {word} is on a kitchen table.',
                                   'A woman is eating {article} {word}.',
                                   '{article} {word} with a few glasses around.',
                                   'A close-up of {article} {word}.'],
                          'vehicle': ['There is one man in {article} {word}.',
                                      '{article} {word} is surrounded by a few people.',
                                      'A woman is posing next to {article} {word}.',
                                      '{article} {word} with a young man next to it.',
                                      'A close-up of {article} {word}.'],
                          'tool': ['There is a man holding {article} {word}.',
                                   '{article} {word} is lying on the ground.',
                                   'A woman is using {article} {word}.',
                                   '{article} {word} with some people in the background.',
                                   'A close-up of {article} {word}.'],
                          'animal': ['There is {article} {word} eating voraciously.',
                                     'A man is feeding {article} {word}.',
                                     'A woman next to {article} {word}.',
                                     '{article} {word} with a little girl staring at it.',
                                     'A close-up of {article} {word}.'],
                          'negative event': ['There is a crowd looking scared because of {article} {word}.',
                                             'Many people are trying to shelter from {article} {word}.',
                                             '{article} {word} happening in a big city.',
                                             '{article} {word} with many people involved.',
                                             'A picture of {article} {word}.'],
                          'social event': ['There is a small crowd attending {article} {word}.',
                                           'A few people are gathered for {article} {word}.',
                                           '{article} {word} attended by a large group of people.',
                                           '{article} {word} with many people involved.',
                                           'A picture of {article} {word}.'],
                          'communication': ['There is a small crowd at {article} {word}.',
                                            'A few people are participating in {article} {word}.',
                                            '{article} {word} in a crowded room.',
                                            '{article} {word} with many people involved.',
                                            'A picture of {article} {word}.'],
                          'sound': ['There is a man hearing {article} {word}.',
                                    'A few people seem to hear {article} {word}.',
                                    '{article} {word} is heard by a few people.',
                                    '{article} {word} with a few people listening to it.',
                                    'A picture of {article} {word}.']}